---
name: Execute precommits

on:
  pull_request:

jobs:
  pre-commit:
    runs-on: [ubuntu-latest]
    name: Execute pre-commit
    steps:
      - uses: actions/checkout@v6
      - uses: asdf-vm/actions/install@v4
        name: Install tools via asdf
      - uses: pre-commit/action@v3.0.1
